
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulcyrebymalrjztgiysr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsY3lyZWJ5bWFscmp6dGdpeXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDA1NDUsImV4cCI6MjA2MTY3NjU0NX0.AI-nCbyUU0k2lEdF6Fk4v4CvQl2-p7DcsjEWeAJ1zpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
